### PR TITLE
possible fixes for: page scrolling, .desktop icon, epdfview-ui.xml path

### PR DESCRIPTION
**Pull request by ncmprhnsbl**
not much activity here for some time? , doing the courteous thing and sharing these minor adjustments:
1. a long standing patch for DATADIR path
2. fixing scroll pages with mouse wheel (ctrl+mouse zoom is not quite right: zooms in but doesn't zoom out)
3. removed specific path in epdfview.desktop (.svg icon is missing from repo.. probably easy enough to recover)

### CODE REVIEW

**Comment by Flow-It** [comment]
I abandoned epdfview months ago. The GTK3 stuff had some surprising issues I didn't want to invest the time into to investigate, and I switched the pdf viewer I'm using personally.
I'll take a look at your changes and eventually merge them, but a) I'm rather busy right now so it might take a couple of weeks, and b) Don't expect any further development here.

**Comment by ncmprhnsbl** [comment]
ok, thanks for the heads up..  and thanks for the work you've put in.  gtk3 issues aside, it seems to be quite usable as is..

**Review by Flow-It — CHANGES_REQUESTED** [review]
3a944ce removed the svg icon from the repo. It looks to me like this was an accident. The proper fix here would be to bring the svg icon back. Could you do that and check that the desktop file still works correctly?

**Comment by ncmprhnsbl** [comment]
what i've done with 31e3d63 :  restored the svg icon  ...but.. instead of having it install in datadir/epdfview/extra, i adjusted the data/meson.build to install it to  datadir/icons/hicolor/scalable , and kept the  .desktop at Icon=epdfview  ...
why? because if the .desktop points at an immutable path ie. /usr/share/epdfview/extra/epdfview.svg, and a user installs with a prefix other than /usr , this will break..
seems to be working ok with my tests..

**Comment by Flow-It** [comment]
Thanks!

**Pull request merged**
